export const ALL_CATEGORY_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_CATEGORY_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_CATEGORY_FAIL = "ALL_PRODUCT_FAIL";

export const NEW_CATEGORY_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_CATEGORY_RESET = "NEW_PRODUCT_RESET";
export const NEW_CATEGORY_FAIL = "NEW_PRODUCT_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_CATEGORY_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_CATEGORY_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_CATEGORY_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_CATEGORY_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_CATEGORY_FAIL = "DELETE_PRODUCT_FAIL";

export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";
export const CATEGORY_DETAILS_FAIL = "CATEGORY_DETAILS_FAIL";
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";